spring:
  devtools:
    restart:
      enabled: true
      exclude: static/**, public/**
    livereload:
      enabled: true
    add-properties: true
  banner:
    location: classpath:benner.txt
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
    database: mysql
  thymeleaf:
    enabled: false
#    prefix: classpath:templates/
#    suffix: .html
#    cache: false
#    check-template: true
#    check-template-location: true
#    enabled: true
#    encoding: UTF-8
#    mode: HTML
server:
  servlet:
    context-path: /
    session:
      timeout: 1
  port: 8080
# 이하는 상수
custom:
  remember-me:
    enckey: kodoku
    remember-me-cookie-key: KODOKU_REMEMBER_ME
